/* Generated by the Nim Compiler v2.2.10 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI553648150 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI33554447 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI553648131 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555870 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555187 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555186 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555184 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217742 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI134217742 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217742.node = NNI134217742;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555184 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555184.node = NNI33555184;
NTI33555186.base = NTI33555183;
NTI33555187.base = NTI33555183;
var NNI33555183 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555186, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555187, name: "up", sons: null}]};
NTI33555183.node = NNI33555183;
var NNI33555179 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555179.node = NNI33555179;
NTI33555183.base = NTI33555179;
NTI33555184.base = NTI33555183;
NTI134217741.base = NTI33555184;
NTI134217742.base = NTI134217741;
var NNI33555870 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555870.node = NNI33555870;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
NTI134217743.base = NTI134217741;
var NNI553648131 = {kind: 2, len: 6, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI33554447, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI33554447, name: "y", sons: null}, 
{kind: 1, offset: "vx", len: 0, typ: NTI33554447, name: "vx", sons: null}, 
{kind: 1, offset: "vy", len: 0, typ: NTI33554447, name: "vy", sons: null}, 
{kind: 1, offset: "density", len: 0, typ: NTI33554447, name: "density", sons: null}, 
{kind: 1, offset: "pressure", len: 0, typ: NTI33554447, name: "pressure", sons: null}]};
NTI553648131.node = NNI553648131;
NTI553648150.base = NTI553648131;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555184;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555184;

function nimAddStrStr(x_p0, y_p1) {
      var L = y_p1.length;
  for (var i = 0; i < L; ++i) {
    x_p0.push(y_p1[i]);
  }
  

  
}

function arrayConstr(len_p0, value_p1, typ_p2) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; ++i) result[i] = nimCopy(null, value_p1, typ_p2);
    return result;
  

  
}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557376 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2924(ti_p2))) {
      result_33557376 = src_p1;
      }
      else {
        result_33557376 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557376 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557376 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557376 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557376 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557376, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557376 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557376 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557376 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557376[i] = nimCopy(result_33557376[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557376 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557376 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557376[i] = nimCopy(result_33557376[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557376 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557376 = src_p1;
      break;
    }

  return result_33557376;

}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function isObj(obj_p0, subclass_p1) {
  var result_33557489 = false;

  BeforeRet: {
    var x_33557490 = obj_p0;
    if ((x_33557490 == subclass_p1)) {
    result_33557489 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557490 == subclass_p1))) break Label2;
          if ((x_33557490 == null)) {
          result_33557489 = false;
          break BeforeRet;
          }
          
          x_33557490 = x_33557490.base;
        }
    };
    result_33557489 = true;
    break BeforeRet;
  };

  return result_33557489;

}

function toJSStr(s_p0) {
  var result_33556953 = null;

    var res_33557019 = newSeq__system_u2562((s_p0).length);
    var i_33557020 = 0;
    var j_33557021 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33557020 < (s_p0).length)) break Label2;
          var c_33557022 = s_p0[i_33557020];
          if ((c_33557022 < 128)) {
          res_33557019[j_33557021] = String.fromCharCode(c_33557022);
          i_33557020 += 1;
          }
          else {
            var helper_33557048 = newSeq__system_u2562(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557049 = c_33557022.toString(16);
                  if ((((code_33557049) == null ? 0 : (code_33557049).length) == 1)) {
                  helper_33557048.push("%0");;
                  }
                  else {
                  helper_33557048.push("%");;
                  }
                  
                  helper_33557048.push(code_33557049);;
                  i_33557020 += 1;
                  if ((((s_p0).length <= i_33557020) || (s_p0[i_33557020] < 128))) {
                  break Label3;
                  }
                  
                  c_33557022 = s_p0[i_33557020];
                }
            };
++excHandler;
            try {
            res_33557019[j_33557021] = decodeURIComponent(helper_33557048.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33557019[j_33557021] = helper_33557048.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33557021 += 1;
        }
    };
    if (res_33557019.length < j_33557021) { for (var i = res_33557019.length ; i < j_33557021 ; ++i) res_33557019.push(null); }
               else { res_33557019.length = j_33557021; };
    result_33556953 = res_33557019.join("");

  return result_33556953;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    e_p0.trace = nimCopy(null, rawWriteStackTrace__system_u2214(), NTI33554449);
    throw e_p0;

  
}

function modInt(a_p0, b_p1) {
        if (b_p1 == 0) raiseDivByZero();
    if (b_p1 == -1 && a_p0 == 2147483647) raiseOverflow();
    return Math.trunc(a_p0 % b_p1);
  

  
}

function divInt(a_p0, b_p1) {
        if (b_p1 == 0) raiseDivByZero();
    if (b_p1 == -1 && a_p0 == 2147483647) raiseOverflow();
    return Math.trunc(a_p0 / b_p1);
  

  
}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557411 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557411 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557411;

}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}
var F = {procname: "module macros", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module options", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/options.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module options", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/options.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module times", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/times.nim", line: 0};
framePtr = F;
F.line = 1377;
F.filename = "times.nim";
if (globalThis.utcInstance_822085401 === undefined) {
  globalThis.utcInstance_822085401 = [null];
}
F.line = 1378;
if (globalThis.localInstance_822085402 === undefined) {
  globalThis.localInstance_822085402 = [null];
}
framePtr = F.prev;
var F = {procname: "module times", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/times.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function newSeq__j0195sph95fluid_u29(len_p0) {
  var result_553648161 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 651;
    F.filename = "system.nim";
    result_553648161 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_553648161[i] = ({x: 0.0, y: 0.0, vx: 0.0, vy: 0.0, density: 0.0, pressure: 0.0}); }  framePtr = F.prev;

  return result_553648161;

}

function add__system_u1972(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function isFatPointer__system_u2924(ti_p0) {
  var result_33557358 = false;

  BeforeRet: {
    result_33557358 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557358;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_335544528 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = (old_335544528 + n_p3), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_335544542 = 0;
      var i_553648323 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_553648323 < n_p3)) break Label4;
            iHEX60gensym4_335544542 = i_553648323;
            result_p0[result_p0_Idx][(old_335544528 + iHEX60gensym4_335544542)] = x_p1.charCodeAt((start_p2 + iHEX60gensym4_335544542));
            i_553648323 += 1;
          }
      };
    };

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));

  
}

function HEX24__systemZdollars_u14(xHEX60gensym0_p0) {
  var result_385875984 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 20;
    F.filename = "dollars.nim";
    result_385875984[0] = nimCopy(null, [], NTI33554449);
    F.line = 21;
    addInt__stdZprivateZdigitsutils_u241(result_385875984, 0, xHEX60gensym0_p0);
  framePtr = F.prev;

  return result_385875984[0];

}

function auxWriteStackTrace__system_u2116(f_p0) {
  var result_33556550 = [[]];

    var it_33556558 = f_p0;
    var i_33556559 = 0;
    var total_33556560 = 0;
    var tempFrames_33556561 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555870);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556558 == null)) && (i_33556559 <= 63))) break Label2;
          tempFrames_33556561[i_33556559].Field0 = it_33556558.procname;
          tempFrames_33556561[i_33556559].Field1 = it_33556558.line;
          tempFrames_33556561[i_33556559].Field2 = it_33556558.filename;
          i_33556559 += 1;
          total_33556560 += 1;
          it_33556558 = it_33556558.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556558 == null))) break Label4;
          total_33556560 += 1;
          it_33556558 = it_33556558.prev;
        }
    };
    result_33556550[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556560 == i_33556559))) {
    nimAddStrStr(result_33556550[0], [40]);;
    nimAddStrStr(result_33556550[0], HEX24__systemZdollars_u14((total_33556560 - i_33556559)));;
    nimAddStrStr(result_33556550[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556594 = 0;
      var colontmp__553648315 = 0;
      colontmp__553648315 = (i_33556559 - 1);
      var res_553648317 = colontmp__553648315;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_553648317)) break Label7;
            j_33556594 = res_553648317;
            nimAddStrStr(result_33556550[0], cstrToNimstr(tempFrames_33556561[j_33556594].Field2));;
            if ((0 < tempFrames_33556561[j_33556594].Field1)) {
            nimAddStrStr(result_33556550[0], [40]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556550, 0, tempFrames_33556561[j_33556594].Field1);
            if (false) {
            nimAddStrStr(result_33556550[0], [44,32]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556550, 0, 0);
            }
            
            nimAddStrStr(result_33556550[0], [41]);;
            }
            
            nimAddStrStr(result_33556550[0], [32,97,116,32]);;
            add__system_u1972(result_33556550, 0, tempFrames_33556561[j_33556594].Field0);
            nimAddStrStr(result_33556550[0], [10]);;
            res_553648317 -= 1;
          }
      };
    };

  return result_33556550[0];

}

function rawWriteStackTrace__system_u2214() {
  var result_33556647 = [];

    if (!((framePtr == null))) {
    result_33556647 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10]).concat(auxWriteStackTrace__system_u2116(framePtr)), NTI33554449);
    }
    else {
      result_33556647 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556647;

}

function newSeq__system_u2562(len_p0) {
  var result_33556998 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 651;
    F.filename = "system.nim";
    result_33556998 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556998[i] = null; }  framePtr = F.prev;

  return result_33556998;

}

function isNimException__system_u2047() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556482 = null;

    if (isNimException__system_u2047()) {
    result_33556482 = lastJSError;
    }
    

  return result_33556482;

}

function raiseDefect() {
    if (isNimException__system_u2047()) {
    var e_33556698 = getCurrentException();
    if (isObj(e_33556698.m_type, NTI33555184)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556698);
    }
    
    e_33556698.trace = nimCopy(null, rawWriteStackTrace__system_u2214(), NTI33554449);
    throw e_33556698;
    }
    
    }
    

  
}

function unhandledException(e_p0) {
    var buf_33556692 = [[]];
    if (!(((e_p0.message).length == 0))) {
    nimAddStrStr(buf_33556692[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    nimAddStrStr(buf_33556692[0], e_p0.message);;
    }
    else {
    nimAddStrStr(buf_33556692[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    nimAddStrStr(buf_33556692[0], [32,91]);;
    add__system_u1972(buf_33556692, 0, e_p0.name);
    nimAddStrStr(buf_33556692[0], [93,10]);;
    nimAddStrStr(buf_33556692[0], rawWriteStackTrace__system_u2214());;
    var cbuf_33556693 = toJSStr(buf_33556692[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556693);
  }
  else {
    throw cbuf_33556693;
  }
  

  
}

function raiseDivByZero() {
    raiseException({message: [100,105,118,105,115,105,111,110,32,98,121,32,122,101,114,111], parent: null, m_type: NTI134217742, name: null, trace: [], up: null}, "DivByZeroDefect");

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function initParticles__j0195sph95fluid_u10(count_p0) {
  var result_553648140 = [];

  var F = {procname: "j01_sph_fluid.initParticles", prev: framePtr, filename: "/home/narayanas/projects/compound/js_suite/j01_sph_fluid.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 15;
    F.filename = "j01_sph_fluid.nim";
    var pool_553648203 = newSeq__j0195sph95fluid_u29(0);
    Label1: {
      F.line = 16;
      var i_553648208 = 0;
      F.line = 96;
      F.filename = "iterators_1.nim";
      var res_553648310 = 1;
      Label2: {
        F.line = 97;
          Label3: while (true) {
          if (!(res_553648310 <= count_p0)) break Label3;
            F.line = 16;
            F.filename = "j01_sph_fluid.nim";
            i_553648208 = res_553648310;
            F.line = 17;
            var p_553648209 = {x: (modInt(i_553648208, 100) * 2.0), y: (divInt(i_553648208, 100) * 2.0), vx: 0.1, vy: -0.5, density: 1000.0, pressure: 0.0};
            F.line = 18;
            var Temporary4 = nimCopy(null, p_553648209, NTI553648131);
            pool_553648203.push(Temporary4);;
            F.line = 102;
            F.filename = "iterators_1.nim";
            res_553648310 = addInt(res_553648310, 1);
          }
      };
    };
    F.line = 19;
    F.filename = "j01_sph_fluid.nim";
    result_553648140 = nimCopy(null, pool_553648203, NTI553648150);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_553648140;

}

function toFloat__system_u1596(i_p0) {
  var result_33556030 = 0.0;

  var F = {procname: "system.toFloat", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 1302;
    F.filename = "system.nim";
    result_33556030 = i_p0;
  framePtr = F.prev;

  return result_33556030;

}

function HEX2F__system_u1608(x_p0, y_p1) {
  var result_33556043 = 0.0;

  var F = {procname: "system./", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 1350;
    F.filename = "system.nim";
    result_33556043 = (toFloat__system_u1596(x_p0) / toFloat__system_u1596(y_p1));
  framePtr = F.prev;

  return result_33556043;

}

function epochTime__pureZtimes_u4732() {
  var result_822088317 = 0.0;

  var F = {procname: "times.epochTime", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/times.nim", line: 0};
  framePtr = F;
    F.line = 2803;
    F.filename = "times.nim";
    result_822088317 = HEX2F__system_u1608(new Date().getTime(), 1000);
  framePtr = F.prev;

  return result_822088317;

}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u14(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u14(a_p1),[32,46,46,32],HEX24__systemZdollars_u14(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function HEX2BHEX3D__pureZstrutils_u2436(x_p0, x_p0_Idx, y_p1) {
  var F = {procname: "+=.+=", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim", line: 0};
  framePtr = F;
    F.line = 337;
    F.filename = "arithmetics.nim";
    x_p0[x_p0_Idx] = (x_p0[x_p0_Idx] + y_p1);
  framePtr = F.prev;

  
}

function sysFatal__stdZassertions_u46(message_p1) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 62;
    F.filename = "fatal.nim";
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert__stdZassertions_u44(msg_p0) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 40;
    F.filename = "assertions.nim";
    sysFatal__stdZassertions_u46(msg_p0);
  framePtr = F.prev;

  
}

function failedAssertImpl__stdZassertions_u86(msg_p0) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 45;
    F.filename = "assertions.nim";
    raiseAssert__stdZassertions_u44(msg_p0);
  framePtr = F.prev;

  
}

function stepSimulation__j0195sph95fluid_u86(particles_p0, particles_p0_Idx, dt_p1) {
  var F = {procname: "j01_sph_fluid.stepSimulation", prev: framePtr, filename: "/home/narayanas/projects/compound/js_suite/j01_sph_fluid.nim", line: 0};
  framePtr = F;
    Label1: {
      F.line = 22;
      F.filename = "j01_sph_fluid.nim";
      var p_553648239 = null;
      F.line = 258;
      F.filename = "iterators.nim";
      var i_553648330 = 0;
      F.line = 259;
      var L_553648331 = (particles_p0[particles_p0_Idx]).length;
      Label2: {
        F.line = 260;
          Label3: while (true) {
          if (!(i_553648330 < L_553648331)) break Label3;
            F.line = 22;
            F.filename = "j01_sph_fluid.nim";
            p_553648239 = particles_p0[particles_p0_Idx][chckIndx(i_553648330, 0, (particles_p0[particles_p0_Idx]).length - 1)];
            F.line = 23;
            HEX2BHEX3D__pureZstrutils_u2436(p_553648239, "x", (p_553648239.vx * dt_p1));
            F.line = 24;
            HEX2BHEX3D__pureZstrutils_u2436(p_553648239, "y", ((p_553648239.vy * dt_p1) + ((4.9 * dt_p1) * dt_p1)));
            F.line = 25;
            HEX2BHEX3D__pureZstrutils_u2436(p_553648239, "vy", (9.8 * dt_p1));
            if ((100.0 < p_553648239.y)) {
            F.line = 27;
            p_553648239.y = 100.0;
            F.line = 28;
            p_553648239.vy = (-(p_553648239.vy) * 0.5);
            }
            
            F.line = 13;
            F.filename = "iterators.nim";
            i_553648330 += 1;
            if (!(((particles_p0[particles_p0_Idx]).length == L_553648331))) {
            F.line = 263;
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators.nim(263, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
  framePtr = F.prev;

  
}

function nimFloatToString__stdZformatfloat_u130(a_p0) {
  var result_402653316 = null;

  var F = {procname: "formatfloat.nimFloatToString", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/formatfloat.nim", line: 0};
  framePtr = F;
    F.line = 107;
    F.filename = "formatfloat.nim";
          function nimOnlyDigitsOrMinus(n) {
        return n.toString().match(/^-?\d+$/);
      }
      if (Number.isSafeInteger(a_p0))
        result_402653316 = a_p0 === 0 && 1 / a_p0 < 0 ? "-0.0" : a_p0+".0";
      else if (isNaN(a_p0)) // Number.isNaN is since ES6
        result_402653316 = "nan";  // or it'll be "NaN"
      else if (!isFinite(a_p0)) // Number.isFinite newer but unnecessary here
        result_402653316 = a_p0 > 0 ? "inf" : "-inf";  // or it'll be [-]Infinity
      else {
        result_402653316 = a_p0+"";
        if(nimOnlyDigitsOrMinus(result_402653316)){
          result_402653316 = a_p0+".0";
        }
      }
    
  framePtr = F.prev;

  return result_402653316;

}

function addFloat__system_u3227(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "addFloat.addFloat", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/formatfloat.nim", line: 0};
  framePtr = F;
    F.line = 141;
    F.filename = "formatfloat.nim";
    add__system_u1972(result_p0, result_p0_Idx, nimFloatToString__stdZformatfloat_u130(x_p1));
  framePtr = F.prev;

  
}

function HEX24__system_u3223(x_p0) {
  var result_33557658 = [[]];

  var F = {procname: "$.$", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 14;
    F.filename = "dollars.nim";
    result_33557658[0] = nimCopy(null, [], NTI33554449);
    F.line = 15;
    addFloat__system_u3227(result_33557658, 0, x_p0);
  framePtr = F.prev;

  return result_33557658[0];

}
var F = {procname: "module j01_sph_fluid", prev: framePtr, filename: "/home/narayanas/projects/compound/js_suite/j01_sph_fluid.nim", line: 0};
framePtr = F;
F.line = 30;
F.filename = "j01_sph_fluid.nim";
var particles_553648284 = [initParticles__j0195sph95fluid_u10(10000)];
F.line = 31;
var start_553648285 = [epochTime__pureZtimes_u4732()];
F.line = 32;
stepSimulation__j0195sph95fluid_u86(particles_553648284, 0, 0.016);
F.line = 33;
var elapsed_553648286 = [(epochTime__pureZtimes_u4732() - start_553648285[0])];
F.line = 35;
rawEcho(makeNimstrLit("[1/10 PASSED] SPH Fluid Simulation (10,000 particles) frame step completed in:"), HEX24__system_u3223(elapsed_553648286[0]), [115,101,99,111,110,100,115,33]);
framePtr = F.prev;
var F = {procname: "module j01_sph_fluid", prev: framePtr, filename: "/home/narayanas/projects/compound/js_suite/j01_sph_fluid.nim", line: 0};
framePtr = F;
framePtr = F.prev;
