/* Generated by the Nim Compiler v2.2.10 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33555185 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217746 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217747 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554444 = {size: 0,kind: 44,base: null,node: null,finalizer: null};
var NTI704643424 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI553648131 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217742 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555870 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555187 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555186 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555184 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI704643075 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI553648145 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI553648142 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI553648139 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NNI553648145 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI704643075, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554449, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554449, name: "Field2", sons: null}]};
NTI553648145.node = NNI553648145;
NTI553648142.base = NTI553648145;
var NNI553648139 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "data", len: 0, typ: NTI553648142, name: "data", sons: null}, 
{kind: 1, offset: "counter", len: 0, typ: NTI33554435, name: "counter", sons: null}]};
NTI553648139.node = NNI553648139;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555184 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555184.node = NNI33555184;
NTI33555186.base = NTI33555183;
NTI33555187.base = NTI33555183;
var NNI33555183 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555186, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555187, name: "up", sons: null}]};
NTI33555183.node = NNI33555183;
var NNI33555179 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555179.node = NNI33555179;
NTI33555183.base = NTI33555179;
NTI33555184.base = NTI33555183;
NTI134217741.base = NTI33555184;
NTI134217743.base = NTI134217741;
var NNI33555870 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555870.node = NNI33555870;
var NNI134217742 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217742.node = NNI134217742;
NTI134217742.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555184;
var NNI553648131 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "kvStore", len: 0, typ: NTI553648139, name: "kvStore", sons: null}, 
{kind: 1, offset: "capacity", len: 0, typ: NTI33554435, name: "capacity", sons: null}]};
NTI553648131.node = NNI553648131;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555184;
var NNI704643424 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554444, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554444, name: "Field1", sons: null}]};
NTI704643424.node = NNI704643424;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555184;
var NNI134217747 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217747.node = NNI134217747;
var NNI134217746 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217746.node = NNI134217746;
var NNI33555185 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555185.node = NNI33555185;
NTI33555185.base = NTI33555183;
NTI134217746.base = NTI33555185;
NTI134217747.base = NTI134217746;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557376 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2924(ti_p2))) {
      result_33557376 = src_p1;
      }
      else {
        result_33557376 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557376 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557376 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557376 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557376 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557376, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557376 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557376 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557376 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557376[i] = nimCopy(result_33557376[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557376 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557376 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557376[i] = nimCopy(result_33557376[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557376 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557376 = src_p1;
      break;
    }

  return result_33557376;

}

function nimAddStrStr(x_p0, y_p1) {
      var L = y_p1.length;
  for (var i = 0; i < L; ++i) {
    x_p0.push(y_p1[i]);
  }
  

  
}

function arrayConstr(len_p0, value_p1, typ_p2) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; ++i) result[i] = nimCopy(null, value_p1, typ_p2);
    return result;
  

  
}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function isObj(obj_p0, subclass_p1) {
  var result_33557489 = false;

  BeforeRet: {
    var x_33557490 = obj_p0;
    if ((x_33557490 == subclass_p1)) {
    result_33557489 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557490 == subclass_p1))) break Label2;
          if ((x_33557490 == null)) {
          result_33557489 = false;
          break BeforeRet;
          }
          
          x_33557490 = x_33557490.base;
        }
    };
    result_33557489 = true;
    break BeforeRet;
  };

  return result_33557489;

}

function toJSStr(s_p0) {
  var result_33556953 = null;

    var res_33557019 = newSeq__system_u2562((s_p0).length);
    var i_33557020 = 0;
    var j_33557021 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33557020 < (s_p0).length)) break Label2;
          var c_33557022 = s_p0[i_33557020];
          if ((c_33557022 < 128)) {
          res_33557019[j_33557021] = String.fromCharCode(c_33557022);
          i_33557020 += 1;
          }
          else {
            var helper_33557048 = newSeq__system_u2562(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557049 = c_33557022.toString(16);
                  if ((((code_33557049) == null ? 0 : (code_33557049).length) == 1)) {
                  helper_33557048.push("%0");;
                  }
                  else {
                  helper_33557048.push("%");;
                  }
                  
                  helper_33557048.push(code_33557049);;
                  i_33557020 += 1;
                  if ((((s_p0).length <= i_33557020) || (s_p0[i_33557020] < 128))) {
                  break Label3;
                  }
                  
                  c_33557022 = s_p0[i_33557020];
                }
            };
++excHandler;
            try {
            res_33557019[j_33557021] = decodeURIComponent(helper_33557048.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33557019[j_33557021] = helper_33557048.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33557021 += 1;
        }
    };
    if (res_33557019.length < j_33557021) { for (var i = res_33557019.length ; i < j_33557021 ; ++i) res_33557019.push(null); }
               else { res_33557019.length = j_33557021; };
    result_33556953 = res_33557019.join("");

  return result_33556953;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    e_p0.trace = nimCopy(null, rawWriteStackTrace__system_u2214(), NTI33554449);
    throw e_p0;

  
}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function divInt(a_p0, b_p1) {
        if (b_p1 == 0) raiseDivByZero();
    if (b_p1 == -1 && a_p0 == 2147483647) raiseOverflow();
    return Math.trunc(a_p0 / b_p1);
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557416 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557416 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557416;

}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557411 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557411 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557411;

}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function mulInt(a_p0, b_p1) {
        var result = a_p0 * b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function eqStrings(a_p0, b_p1) {
        if (a_p0 == b_p1) return true;
    if (a_p0 === null && b_p1.length == 0) return true;
    if (b_p1 === null && a_p0.length == 0) return true;
    if ((!a_p0) || (!b_p1)) return false;
    var alen = a_p0.length;
    if (alen != b_p1.length) return false;
    for (var i = 0; i < alen; ++i)
      if (a_p0[i] != b_p1[i]) return false;
    return true;
  

  
}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
framePtr = F;
F.line = 219;
F.filename = "hashes.nim";
var objectID_704643250 = [0];
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer__system_u2924(ti_p0) {
  var result_33557358 = false;

  BeforeRet: {
    result_33557358 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557358;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function nextPowerOfTwo__pureZmath_u226(x_p0) {
  var result_754974948 = 0;

    result_754974948 = (x_p0 - 1);
    result_754974948 = (result_754974948 | (result_754974948 >> (16 & 31)));
    result_754974948 = (result_754974948 | (result_754974948 >> (8 & 31)));
    result_754974948 = (result_754974948 | (result_754974948 >> (4 & 31)));
    result_754974948 = (result_754974948 | (result_754974948 >> (2 & 31)));
    result_754974948 = (result_754974948 | (result_754974948 >> (1 & 31)));
    result_754974948 += (1 + ((x_p0 <= 0) ? 1 : 0));

  return result_754974948;

}

function add__system_u1972(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_335544528 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = (old_335544528 + n_p3), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_335544542 = 0;
      var i_553649730 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_553649730 < n_p3)) break Label4;
            iHEX60gensym4_335544542 = i_553649730;
            result_p0[result_p0_Idx][(old_335544528 + iHEX60gensym4_335544542)] = x_p1.charCodeAt((start_p2 + iHEX60gensym4_335544542));
            i_553649730 += 1;
          }
      };
    };

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));

  
}

function HEX24__systemZdollars_u14(xHEX60gensym0_p0) {
  var result_385875984 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 20;
    F.filename = "dollars.nim";
    result_385875984[0] = nimCopy(null, [], NTI33554449);
    F.line = 21;
    addInt__stdZprivateZdigitsutils_u241(result_385875984, 0, xHEX60gensym0_p0);
  framePtr = F.prev;

  return result_385875984[0];

}

function auxWriteStackTrace__system_u2116(f_p0) {
  var result_33556550 = [[]];

    var it_33556558 = f_p0;
    var i_33556559 = 0;
    var total_33556560 = 0;
    var tempFrames_33556561 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555870);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556558 == null)) && (i_33556559 <= 63))) break Label2;
          tempFrames_33556561[i_33556559].Field0 = it_33556558.procname;
          tempFrames_33556561[i_33556559].Field1 = it_33556558.line;
          tempFrames_33556561[i_33556559].Field2 = it_33556558.filename;
          i_33556559 += 1;
          total_33556560 += 1;
          it_33556558 = it_33556558.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556558 == null))) break Label4;
          total_33556560 += 1;
          it_33556558 = it_33556558.prev;
        }
    };
    result_33556550[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556560 == i_33556559))) {
    nimAddStrStr(result_33556550[0], [40]);;
    nimAddStrStr(result_33556550[0], HEX24__systemZdollars_u14((total_33556560 - i_33556559)));;
    nimAddStrStr(result_33556550[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556594 = 0;
      var colontmp__553649722 = 0;
      colontmp__553649722 = (i_33556559 - 1);
      var res_553649724 = colontmp__553649722;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_553649724)) break Label7;
            j_33556594 = res_553649724;
            nimAddStrStr(result_33556550[0], cstrToNimstr(tempFrames_33556561[j_33556594].Field2));;
            if ((0 < tempFrames_33556561[j_33556594].Field1)) {
            nimAddStrStr(result_33556550[0], [40]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556550, 0, tempFrames_33556561[j_33556594].Field1);
            if (false) {
            nimAddStrStr(result_33556550[0], [44,32]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556550, 0, 0);
            }
            
            nimAddStrStr(result_33556550[0], [41]);;
            }
            
            nimAddStrStr(result_33556550[0], [32,97,116,32]);;
            add__system_u1972(result_33556550, 0, tempFrames_33556561[j_33556594].Field0);
            nimAddStrStr(result_33556550[0], [10]);;
            res_553649724 -= 1;
          }
      };
    };

  return result_33556550[0];

}

function rawWriteStackTrace__system_u2214() {
  var result_33556647 = [];

    if (!((framePtr == null))) {
    result_33556647 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10]).concat(auxWriteStackTrace__system_u2116(framePtr)), NTI33554449);
    }
    else {
      result_33556647 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556647;

}

function newSeq__system_u2562(len_p0) {
  var result_33556998 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 651;
    F.filename = "system.nim";
    result_33556998 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556998[i] = null; }  framePtr = F.prev;

  return result_33556998;

}

function isNimException__system_u2047() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556482 = null;

    if (isNimException__system_u2047()) {
    result_33556482 = lastJSError;
    }
    

  return result_33556482;

}

function raiseDefect() {
    if (isNimException__system_u2047()) {
    var e_33556698 = getCurrentException();
    if (isObj(e_33556698.m_type, NTI33555184)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556698);
    }
    
    e_33556698.trace = nimCopy(null, rawWriteStackTrace__system_u2214(), NTI33554449);
    throw e_33556698;
    }
    
    }
    

  
}

function unhandledException(e_p0) {
    var buf_33556692 = [[]];
    if (!(((e_p0.message).length == 0))) {
    nimAddStrStr(buf_33556692[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    nimAddStrStr(buf_33556692[0], e_p0.message);;
    }
    else {
    nimAddStrStr(buf_33556692[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    nimAddStrStr(buf_33556692[0], [32,91]);;
    add__system_u1972(buf_33556692, 0, e_p0.name);
    nimAddStrStr(buf_33556692[0], [93,10]);;
    nimAddStrStr(buf_33556692[0], rawWriteStackTrace__system_u2214());;
    var cbuf_33556693 = toJSStr(buf_33556692[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556693);
  }
  else {
    throw cbuf_33556693;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function raiseDivByZero() {
    raiseException({message: [100,105,118,105,115,105,111,110,32,98,121,32,122,101,114,111], parent: null, m_type: NTI134217742, name: null, trace: [], up: null}, "DivByZeroDefect");

  
}

function slotsNeeded__pureZcollectionsZtables_u42(count_p0) {
  var result_687865900 = 0;

  var F = {procname: "tables.slotsNeeded", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/hashcommon.nim", line: 0};
  framePtr = F;
    F.line = 39;
    F.filename = "hashcommon.nim";
    result_687865900 = nextPowerOfTwo__pureZmath_u226(addInt(addInt(divInt(count_p0, 2), count_p0), 4));
  framePtr = F.prev;

  return result_687865900;

}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function initTable__j0395chronokv95playground_u28(initialSize_p0) {
  var result_553648160 = ({data: [], counter: 0});

  var F = {procname: "initTable.initTable", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/tables.nim", line: 0};
  framePtr = F;
    F.line = 281;
    F.filename = "tables.nim";
    result_553648160 = nimCopy(result_553648160, ({data: [], counter: 0}), NTI553648139);
    F.line = 182;
    F.filename = "tableimpl.nim";
    var correctSizeHEX60gensym0_553648169 = slotsNeeded__pureZcollectionsZtables_u42(chckRange(initialSize_p0, 0, 2147483647));
    F.line = 186;
    result_553648160.counter = 0;
    F.line = 187;
    result_553648160.data = new Array(chckRange(correctSizeHEX60gensym0_553648169, 0, 2147483647)); for (var i = 0 ; i < chckRange(correctSizeHEX60gensym0_553648169, 0, 2147483647) ; ++i) { result_553648160.data[i] = {Field0: 0, Field1: [], Field2: []}; }  framePtr = F.prev;

  return result_553648160;

}

function createMemTable__j0395chronokv95playground_u13(cap_p0) {
  var result_553648143 = ({kvStore: ({data: [], counter: 0}), capacity: 0});

  var F = {procname: "j03_chronokv_playground.createMemTable", prev: framePtr, filename: "/home/narayanas/projects/compound/js_suite/j03_chronokv_playground.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 11;
    F.filename = "j03_chronokv_playground.nim";
    result_553648143 = nimCopy(result_553648143, {kvStore: initTable__j0395chronokv95playground_u28(32), capacity: cap_p0}, NTI553648131);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_553648143;

}

function lenU__pureZhashes_u502(s_p0) {
  var result_704643576 = 0n;

  var F = {procname: "hashes.lenU", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 402;
    F.filename = "hashes.nim";
    result_704643576 = BigInt.asUintN(64, BigInt((s_p0).length));
  framePtr = F.prev;

  return result_704643576;

}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u14(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u14(a_p1),[32,46,46,32],HEX24__systemZdollars_u14(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function load8e__pureZhashes_u390(s_p0, o_p1) {
  var result_704643465 = 0n;

  var F = {procname: "hashes.load8e", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 315;
    F.filename = "hashes.nim";
    result_704643465 = (((((((BigInt.asUintN(64, BigInt(s_p0[chckIndx(addInt(o_p1, 7), 0, (s_p0).length - 1)]) << (BigInt(56) & 63n)) | BigInt.asUintN(64, BigInt(s_p0[chckIndx(addInt(o_p1, 6), 0, (s_p0).length - 1)]) << (BigInt(48) & 63n))) | BigInt.asUintN(64, BigInt(s_p0[chckIndx(addInt(o_p1, 5), 0, (s_p0).length - 1)]) << (BigInt(40) & 63n))) | BigInt.asUintN(64, BigInt(s_p0[chckIndx(addInt(o_p1, 4), 0, (s_p0).length - 1)]) << (BigInt(32) & 63n))) | BigInt.asUintN(64, BigInt(s_p0[chckIndx(addInt(o_p1, 3), 0, (s_p0).length - 1)]) << (BigInt(24) & 63n))) | BigInt.asUintN(64, BigInt(s_p0[chckIndx(addInt(o_p1, 2), 0, (s_p0).length - 1)]) << (BigInt(16) & 63n))) | BigInt.asUintN(64, BigInt(s_p0[chckIndx(addInt(o_p1, 1), 0, (s_p0).length - 1)]) << (BigInt(8) & 63n))) | BigInt(s_p0[chckIndx(addInt(o_p1, 0), 0, (s_p0).length - 1)]));
  framePtr = F.prev;

  return result_704643465;

}

function load8__pureZhashes_u426(s_p0, o_p1) {
  var result_704643501 = 0n;

  var F = {procname: "hashes.load8", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 334;
    F.filename = "hashes.nim";
    result_704643501 = load8e__pureZhashes_u390(s_p0, o_p1);
  framePtr = F.prev;

  return result_704643501;

}

function rotR__pureZhashes_u515(v_p0, bits_p1) {
  var result_704643590 = 0n;

  var F = {procname: "hashes.rotR", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 407;
    F.filename = "hashes.nim";
    result_704643590 = ((v_p0 >> (BigInt(bits_p1) & 63n)) | BigInt.asUintN(64, v_p0 << (BigInt(subInt(64, bits_p1)) & 63n)));
  framePtr = F.prev;

  return result_704643590;

}

function len16__pureZhashes_u527(u_p0, v_p1, mul_p2) {
  var result_704643603 = 0n;

  var F = {procname: "hashes.len16", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 410;
    F.filename = "hashes.nim";
    F.line = 410;
    var a_704643604 = BigInt.asUintN(64, ((u_p0 ^ v_p1) * mul_p2));
    F.line = 411;
    a_704643604 = (a_704643604 ^ (a_704643604 >> (BigInt(47) & 63n)));
    F.line = 412;
    var b_704643609 = BigInt.asUintN(64, ((v_p1 ^ a_704643604) * mul_p2));
    F.line = 413;
    b_704643609 = (b_704643609 ^ (b_704643609 >> (BigInt(47) & 63n)));
    result_704643603 = BigInt.asUintN(64, (b_704643609 * mul_p2));
  framePtr = F.prev;

  return result_704643603;

}

function load4e__pureZhashes_u374(s_p0, o_p1) {
  var result_704643449 = 0;

  var F = {procname: "hashes.load4e", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 309;
    F.filename = "hashes.nim";
    result_704643449 = (((((((((s_p0[chckIndx(addInt(o_p1, 3), 0, (s_p0).length - 1)] >>> 0) << (24 & 31)) >>> 0) | (((s_p0[chckIndx(addInt(o_p1, 2), 0, (s_p0).length - 1)] >>> 0) << (16 & 31)) >>> 0)) >>> 0) | (((s_p0[chckIndx(addInt(o_p1, 1), 0, (s_p0).length - 1)] >>> 0) << (8 & 31)) >>> 0)) >>> 0) | (s_p0[chckIndx(addInt(o_p1, 0), 0, (s_p0).length - 1)] >>> 0)) >>> 0);
  framePtr = F.prev;

  return result_704643449;

}

function load4__pureZhashes_u422(s_p0, o_p1) {
  var result_704643497 = 0;

  var F = {procname: "hashes.load4", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 326;
    F.filename = "hashes.nim";
    result_704643497 = load4e__pureZhashes_u374(s_p0, o_p1);
  framePtr = F.prev;

  return result_704643497;

}

function shiftMix__pureZhashes_u508(v_p0) {
  var result_704643582 = 0n;

  var F = {procname: "hashes.shiftMix", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 404;
    F.filename = "hashes.nim";
    result_704643582 = (v_p0 ^ (v_p0 >> (BigInt(47) & 63n)));
  framePtr = F.prev;

  return result_704643582;

}

function len0_16__pureZhashes_u542(s_p0) {
    var Temporary1;

  var result_704643616 = 0n;

  var F = {procname: "hashes.len0_16", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 417;
    F.filename = "hashes.nim";
    if ((8 <= (s_p0).length)) {
    F.line = 418;
    var mul_704643620 = BigInt.asUintN(64, (11160318154034397263n + BigInt.asUintN(64, (2n * lenU__pureZhashes_u502(s_p0)))));
    F.line = 419;
    var a_704643621 = BigInt.asUintN(64, (load8__pureZhashes_u426(s_p0, 0) + 11160318154034397263n));
    F.line = 420;
    var b_704643625 = load8__pureZhashes_u426(s_p0, subInt((s_p0).length, 8));
    F.line = 421;
    var c_704643626 = BigInt.asUintN(64, (BigInt.asUintN(64, (rotR__pureZhashes_u515(b_704643625, 37) * mul_704643620)) + a_704643621));
    F.line = 422;
    var d_704643627 = BigInt.asUintN(64, (BigInt.asUintN(64, (rotR__pureZhashes_u515(a_704643621, 25) + b_704643625)) * mul_704643620));
    Temporary1 = len16__pureZhashes_u527(c_704643626, d_704643627, mul_704643620);
    }
    else {
    if ((4 <= (s_p0).length)) {
    F.line = 425;
    var mul_704643631 = BigInt.asUintN(64, (11160318154034397263n + BigInt.asUintN(64, (2n * lenU__pureZhashes_u502(s_p0)))));
    F.line = 426;
    var a_704643632 = BigInt(load4__pureZhashes_u422(s_p0, 0));
    Temporary1 = len16__pureZhashes_u527(BigInt.asUintN(64, (lenU__pureZhashes_u502(s_p0) + BigInt.asUintN(64, a_704643632 << (BigInt(3) & 63n)))), BigInt(load4__pureZhashes_u422(s_p0, subInt((s_p0).length, 4))), mul_704643631);
    }
    else {
    if ((0 < (s_p0).length)) {
    F.line = 429;
    var a_704643643 = (s_p0[chckIndx(0, 0, (s_p0).length - 1)] >>> 0);
    F.line = 430;
    var b_704643651 = (s_p0[chckIndx(((s_p0).length >> (1 & 31)), 0, (s_p0).length - 1)] >>> 0);
    F.line = 431;
    var c_704643655 = (s_p0[chckIndx(subInt((s_p0).length, 1), 0, (s_p0).length - 1)] >>> 0);
    F.line = 432;
    var y_704643660 = ((a_704643643 + ((b_704643651 << (8 & 31)) >>> 0)) >>> 0);
    F.line = 433;
    var z_704643665 = BigInt.asUintN(64, (lenU__pureZhashes_u502(s_p0) + BigInt(((c_704643655 << (2 & 31)) >>> 0))));
    Temporary1 = BigInt.asUintN(64, (shiftMix__pureZhashes_u508((BigInt.asUintN(64, (BigInt(y_704643660) * 11160318154034397263n)) ^ BigInt.asUintN(64, (z_704643665 * 14097894508562428199n)))) * 11160318154034397263n));
    }
    else {
    Temporary1 = 11160318154034397263n;
    }
    }}
    result_704643616 = Temporary1;
  framePtr = F.prev;

  return result_704643616;

}

function len17_32__pureZhashes_u594(s_p0) {
  var result_704643668 = 0n;

  var F = {procname: "hashes.len17_32", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 438;
    F.filename = "hashes.nim";
    F.line = 438;
    var mul_704643669 = BigInt.asUintN(64, (11160318154034397263n + BigInt.asUintN(64, (2n * lenU__pureZhashes_u502(s_p0)))));
    F.line = 439;
    var a_704643670 = BigInt.asUintN(64, (load8__pureZhashes_u426(s_p0, 0) * 13011662864482103923n));
    F.line = 440;
    var b_704643671 = load8__pureZhashes_u426(s_p0, 8);
    F.line = 441;
    var c_704643675 = BigInt.asUintN(64, (load8__pureZhashes_u426(s_p0, subInt((s_p0).length, 8)) * mul_704643669));
    F.line = 442;
    var d_704643679 = BigInt.asUintN(64, (load8__pureZhashes_u426(s_p0, subInt((s_p0).length, 16)) * 11160318154034397263n));
    result_704643668 = len16__pureZhashes_u527(BigInt.asUintN(64, (BigInt.asUintN(64, (rotR__pureZhashes_u515(BigInt.asUintN(64, (a_704643670 + b_704643671)), 43) + rotR__pureZhashes_u515(c_704643675, 30))) + d_704643679)), BigInt.asUintN(64, (BigInt.asUintN(64, (a_704643670 + rotR__pureZhashes_u515(BigInt.asUintN(64, (b_704643671 + 11160318154034397263n)), 18))) + c_704643675)), mul_704643669);
  framePtr = F.prev;

  return result_704643668;

}

function len33_64__pureZhashes_u608(s_p0) {
  var result_704643682 = 0n;

  var F = {procname: "hashes.len33_64", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 446;
    F.filename = "hashes.nim";
    F.line = 446;
    var mul_704643683 = BigInt.asUintN(64, (11160318154034397263n + BigInt.asUintN(64, (2n * lenU__pureZhashes_u502(s_p0)))));
    F.line = 447;
    var a_704643684 = BigInt.asUintN(64, (load8__pureZhashes_u426(s_p0, 0) * 11160318154034397263n));
    F.line = 448;
    var b_704643685 = load8__pureZhashes_u426(s_p0, 8);
    F.line = 449;
    var c_704643689 = BigInt.asUintN(64, (load8__pureZhashes_u426(s_p0, subInt((s_p0).length, 8)) * mul_704643683));
    F.line = 450;
    var d_704643693 = BigInt.asUintN(64, (load8__pureZhashes_u426(s_p0, subInt((s_p0).length, 16)) * 11160318154034397263n));
    F.line = 451;
    var y_704643694 = BigInt.asUintN(64, (BigInt.asUintN(64, (rotR__pureZhashes_u515(BigInt.asUintN(64, (a_704643684 + b_704643685)), 43) + rotR__pureZhashes_u515(c_704643689, 30))) + d_704643693));
    F.line = 452;
    var z_704643695 = len16__pureZhashes_u527(y_704643694, BigInt.asUintN(64, (BigInt.asUintN(64, (a_704643684 + rotR__pureZhashes_u515(BigInt.asUintN(64, (b_704643685 + 11160318154034397263n)), 18))) + c_704643689)), mul_704643683);
    F.line = 453;
    var e_704643696 = BigInt.asUintN(64, (load8__pureZhashes_u426(s_p0, 16) * mul_704643683));
    F.line = 454;
    var f_704643697 = load8__pureZhashes_u426(s_p0, 24);
    F.line = 455;
    var g_704643701 = BigInt.asUintN(64, (BigInt.asUintN(64, (y_704643694 + load8__pureZhashes_u426(s_p0, subInt((s_p0).length, 32)))) * mul_704643683));
    F.line = 456;
    var h_704643705 = BigInt.asUintN(64, (BigInt.asUintN(64, (z_704643695 + load8__pureZhashes_u426(s_p0, subInt((s_p0).length, 24)))) * mul_704643683));
    result_704643682 = len16__pureZhashes_u527(BigInt.asUintN(64, (BigInt.asUintN(64, (rotR__pureZhashes_u515(BigInt.asUintN(64, (e_704643696 + f_704643697)), 43) + rotR__pureZhashes_u515(g_704643701, 30))) + h_704643705)), BigInt.asUintN(64, (BigInt.asUintN(64, (e_704643696 + rotR__pureZhashes_u515(BigInt.asUintN(64, (f_704643697 + a_704643684)), 18))) + g_704643701)), mul_704643683);
  framePtr = F.prev;

  return result_704643682;

}

function weakLen32withSeeds2__pureZhashes_u639(w_p0, x_p1, y_p2, z_p3, a_p4, b_p5) {
  var result_704643718 = {Field0: 0n, Field1: 0n};

  var F = {procname: "hashes.weakLen32withSeeds2", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 462;
    F.filename = "hashes.nim";
    var a_704643719 = BigInt.asUintN(64, (a_p4 + w_p0));
    F.line = 463;
    var b_704643720 = rotR__pureZhashes_u515(BigInt.asUintN(64, (BigInt.asUintN(64, (b_p5 + a_704643719)) + z_p3)), 21);
    F.line = 464;
    var c_704643721 = a_704643719;
    F.line = 465;
    a_704643719 = BigInt.asUintN(64, a_704643719 + BigInt(x_p1));
    F.line = 466;
    a_704643719 = BigInt.asUintN(64, a_704643719 + BigInt(y_p2));
    F.line = 467;
    b_704643720 = BigInt.asUintN(64, b_704643720 + BigInt(rotR__pureZhashes_u515(a_704643719, 44)));
    F.line = 468;
    result_704643718["Field0"] = BigInt.asUintN(64, (a_704643719 + z_p3));
    F.line = 469;
    result_704643718["Field1"] = BigInt.asUintN(64, (b_704643720 + c_704643721));
  framePtr = F.prev;

  return result_704643718;

}

function weakLen32withSeeds__pureZhashes_u662(s_p0, o_p1, a_p2, b_p3) {
  var result_704643739 = {Field0: 0n, Field1: 0n};

  var F = {procname: "hashes.weakLen32withSeeds", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 472;
    F.filename = "hashes.nim";
    result_704643739 = nimCopy(result_704643739, weakLen32withSeeds2__pureZhashes_u639(load8__pureZhashes_u426(s_p0, o_p1), load8__pureZhashes_u426(s_p0, addInt(o_p1, 8)), load8__pureZhashes_u426(s_p0, addInt(o_p1, 16)), load8__pureZhashes_u426(s_p0, addInt(o_p1, 24)), a_p2, b_p3), NTI704643424);
  framePtr = F.prev;

  return result_704643739;

}

function hashFarm__pureZhashes_u685(s_p0) {
  var result_704643759 = 0n;

  var F = {procname: "hashes.hashFarm", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 476;
    F.filename = "hashes.nim";
    if (((s_p0).length <= 16)) {
    F.line = 476;
    result_704643759 = len0_16__pureZhashes_u542(s_p0);
    break BeforeRet;
    }
    
    if (((s_p0).length <= 32)) {
    F.line = 477;
    result_704643759 = len17_32__pureZhashes_u594(s_p0);
    break BeforeRet;
    }
    
    if (((s_p0).length <= 64)) {
    F.line = 478;
    result_704643759 = len33_64__pureZhashes_u608(s_p0);
    break BeforeRet;
    }
    
    F.line = 481;
    var o_704643770 = 0;
    F.line = 482;
    var x_704643771 = 81n;
    F.line = 483;
    var y_704643772 = 2480279821605975764n;
    F.line = 484;
    var z_704643773 = BigInt.asUintN(64, (shiftMix__pureZhashes_u508(BigInt.asUintN(64, (BigInt.asUintN(64, (y_704643772 * 11160318154034397263n)) + 113n))) * 11160318154034397263n));
    F.line = 485;
    var v_704643779 = nimCopy(null, {Field0: 0n, Field1: 0n}, NTI704643424);
    F.line = 485;
    var w_704643784 = nimCopy(null, {Field0: 0n, Field1: 0n}, NTI704643424);
    F.line = 486;
    x_704643771 = BigInt.asUintN(64, (BigInt.asUintN(64, (x_704643771 * 11160318154034397263n)) + load8__pureZhashes_u426(s_p0, 0)));
    F.line = 487;
    var eos_704643788 = mulInt(divInt(subInt((s_p0).length, 1), 64), 64);
    F.line = 488;
    var last64_704643792 = subInt(addInt(eos_704643788, (subInt((s_p0).length, 1) & 63)), 63);
    Label1: {
      F.line = 489;
        Label2: while (true) {
        if (!true) break Label2;
          F.line = 490;
          x_704643771 = BigInt.asUintN(64, (rotR__pureZhashes_u515(BigInt.asUintN(64, (BigInt.asUintN(64, (BigInt.asUintN(64, (x_704643771 + y_704643772)) + v_704643779["Field0"])) + load8__pureZhashes_u426(s_p0, addInt(o_704643770, 8)))), 37) * 13011662864482103923n));
          F.line = 491;
          y_704643772 = BigInt.asUintN(64, (rotR__pureZhashes_u515(BigInt.asUintN(64, (BigInt.asUintN(64, (y_704643772 + v_704643779["Field1"])) + load8__pureZhashes_u426(s_p0, addInt(o_704643770, 48)))), 42) * 13011662864482103923n));
          F.line = 492;
          x_704643771 = (x_704643771 ^ w_704643784["Field1"]);
          F.line = 493;
          y_704643772 = BigInt.asUintN(64, y_704643772 + BigInt(BigInt.asUintN(64, (v_704643779["Field0"] + load8__pureZhashes_u426(s_p0, addInt(o_704643770, 40))))));
          F.line = 494;
          z_704643773 = BigInt.asUintN(64, (rotR__pureZhashes_u515(BigInt.asUintN(64, (z_704643773 + w_704643784["Field0"])), 33) * 13011662864482103923n));
          F.line = 495;
          v_704643779 = nimCopy(v_704643779, weakLen32withSeeds__pureZhashes_u662(s_p0, addInt(o_704643770, 0), BigInt.asUintN(64, (v_704643779["Field1"] * 13011662864482103923n)), BigInt.asUintN(64, (x_704643771 + w_704643784["Field0"]))), NTI704643424);
          F.line = 496;
          w_704643784 = nimCopy(w_704643784, weakLen32withSeeds__pureZhashes_u662(s_p0, addInt(o_704643770, 32), BigInt.asUintN(64, (z_704643773 + w_704643784["Field1"])), BigInt.asUintN(64, (y_704643772 + load8__pureZhashes_u426(s_p0, addInt(o_704643770, 16))))), NTI704643424);
          F.line = 497;
          F.line = 497;
          var HEX3Atmp_553649737 = z_704643773;
          F.line = 497;
          z_704643773 = x_704643771;
          F.line = 497;
          x_704643771 = HEX3Atmp_553649737;
          F.line = 498;
          o_704643770 = addInt(o_704643770, 64);
          if ((o_704643770 == eos_704643788)) {
          F.line = 499;
          break Label1;
          }
          
        }
    };
    F.line = 500;
    var mul_704643810 = BigInt.asUintN(64, (13011662864482103923n + BigInt.asUintN(64, (z_704643773 & 255n) << (BigInt(1) & 63n))));
    F.line = 501;
    o_704643770 = last64_704643792;
    F.line = 502;
    w_704643784["Field0"] = BigInt.asUintN(64, w_704643784["Field0"] + BigInt((BigInt.asUintN(64, (lenU__pureZhashes_u502(s_p0) - 1n)) & 63n)));
    F.line = 503;
    v_704643779["Field0"] = BigInt.asUintN(64, v_704643779["Field0"] + BigInt(w_704643784["Field0"]));
    F.line = 504;
    w_704643784["Field0"] = BigInt.asUintN(64, w_704643784["Field0"] + BigInt(v_704643779["Field0"]));
    F.line = 505;
    x_704643771 = BigInt.asUintN(64, (rotR__pureZhashes_u515(BigInt.asUintN(64, (BigInt.asUintN(64, (BigInt.asUintN(64, (x_704643771 + y_704643772)) + v_704643779["Field0"])) + load8__pureZhashes_u426(s_p0, addInt(o_704643770, 8)))), 37) * mul_704643810));
    F.line = 506;
    y_704643772 = BigInt.asUintN(64, (rotR__pureZhashes_u515(BigInt.asUintN(64, (BigInt.asUintN(64, (y_704643772 + v_704643779["Field1"])) + load8__pureZhashes_u426(s_p0, addInt(o_704643770, 48)))), 42) * mul_704643810));
    F.line = 507;
    x_704643771 = (x_704643771 ^ BigInt.asUintN(64, (w_704643784["Field1"] * 9n)));
    F.line = 508;
    y_704643772 = BigInt.asUintN(64, y_704643772 + BigInt(BigInt.asUintN(64, (BigInt.asUintN(64, (v_704643779["Field0"] * 9n)) + load8__pureZhashes_u426(s_p0, addInt(o_704643770, 40))))));
    F.line = 509;
    z_704643773 = BigInt.asUintN(64, (rotR__pureZhashes_u515(BigInt.asUintN(64, (z_704643773 + w_704643784["Field0"])), 33) * mul_704643810));
    F.line = 510;
    v_704643779 = nimCopy(v_704643779, weakLen32withSeeds__pureZhashes_u662(s_p0, addInt(o_704643770, 0), BigInt.asUintN(64, (v_704643779["Field1"] * mul_704643810)), BigInt.asUintN(64, (x_704643771 + w_704643784["Field0"]))), NTI704643424);
    F.line = 511;
    w_704643784 = nimCopy(w_704643784, weakLen32withSeeds__pureZhashes_u662(s_p0, addInt(o_704643770, 32), BigInt.asUintN(64, (z_704643773 + w_704643784["Field1"])), BigInt.asUintN(64, (y_704643772 + load8__pureZhashes_u426(s_p0, addInt(o_704643770, 16))))), NTI704643424);
    F.line = 512;
    F.line = 512;
    var HEX3Atmp_553649738 = z_704643773;
    F.line = 512;
    z_704643773 = x_704643771;
    F.line = 512;
    x_704643771 = HEX3Atmp_553649738;
    result_704643759 = len16__pureZhashes_u527(BigInt.asUintN(64, (BigInt.asUintN(64, (len16__pureZhashes_u527(v_704643779["Field0"], w_704643784["Field0"], mul_704643810) + BigInt.asUintN(64, (shiftMix__pureZhashes_u508(y_704643772) * 14097894508562428199n)))) + z_704643773)), BigInt.asUintN(64, (len16__pureZhashes_u527(v_704643779["Field1"], w_704643784["Field1"], mul_704643810) + x_704643771)), mul_704643810);
  };
  framePtr = F.prev;

  return result_704643759;

}

function hash__pureZhashes_u761(x_p0) {
  var result_704643835 = 0;

  var F = {procname: "hashes.hash", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/hashes.nim", line: 0};
  framePtr = F;
    F.line = 531;
    F.filename = "hashes.nim";
    result_704643835 = Number(BigInt.asIntN(32, hashFarm__pureZhashes_u685((x_p0.slice(0, (x_p0).length - 1 + 1)))));
  framePtr = F.prev;

  return result_704643835;

}

function isFilled__pureZcollectionsZtables_u31(hcode_p0) {
  var result_687865889 = false;

  var F = {procname: "tables.isFilled", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/hashcommon.nim", line: 0};
  framePtr = F;
    F.line = 27;
    F.filename = "hashcommon.nim";
    result_687865889 = !((hcode_p0 == 0));
  framePtr = F.prev;

  return result_687865889;

}

function nextTry__pureZcollectionsZtables_u34(h_p0, maxHash_p1) {
  var result_687865893 = 0;

  var F = {procname: "tables.nextTry", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/hashcommon.nim", line: 0};
  framePtr = F;
    F.line = 30;
    F.filename = "hashcommon.nim";
    result_687865893 = (addInt(h_p0, 1) & maxHash_p1);
  framePtr = F.prev;

  return result_687865893;

}

function rawGet__j0395chronokv95playground_u199(t_p0, key_p1, hc_p2, hc_p2_Idx) {
  var result_553648333 = 0;

  var F = {procname: "rawGet.rawGet", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/hashcommon.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 59;
    F.filename = "hashcommon.nim";
    hc_p2[hc_p2_Idx] = hash__pureZhashes_u761(key_p1);
    if ((hc_p2[hc_p2_Idx] == 0)) {
    F.line = 64;
    hc_p2[hc_p2_Idx] = 314159265;
    }
    
    if (((t_p0.data).length == 0)) {
    F.line = 43;
    result_553648333 = (-1);
    break BeforeRet;
    }
    
    F.line = 44;
    var h_553648383 = (hc_p2[hc_p2_Idx] & (t_p0.data).length - 1);
    Label1: {
      F.line = 45;
        Label2: while (true) {
        if (!isFilled__pureZcollectionsZtables_u31(t_p0.data[chckIndx(h_553648383, 0, (t_p0.data).length - 1)].Field0)) break Label2;
          if (((t_p0.data[chckIndx(h_553648383, 0, (t_p0.data).length - 1)].Field0 == hc_p2[hc_p2_Idx]) && eqStrings(t_p0.data[chckIndx(h_553648383, 0, (t_p0.data).length - 1)].Field1, key_p1))) {
          F.line = 51;
          result_553648333 = h_553648383;
          break BeforeRet;
          }
          
          F.line = 52;
          h_553648383 = nextTry__pureZcollectionsZtables_u34(h_553648383, (t_p0.data).length - 1);
        }
    };
    F.line = 53;
    result_553648333 = subInt((-1), h_553648383);
  };
  framePtr = F.prev;

  return result_553648333;

}

function sysFatal__stdZassertions_u46(message_p1) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 62;
    F.filename = "fatal.nim";
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert__stdZassertions_u44(msg_p0) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 40;
    F.filename = "assertions.nim";
    sysFatal__stdZassertions_u46(msg_p0);
  framePtr = F.prev;

  
}

function failedAssertImpl__stdZassertions_u86(msg_p0) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 45;
    F.filename = "assertions.nim";
    raiseAssert__stdZassertions_u44(msg_p0);
  framePtr = F.prev;

  
}

function mustRehash__j0395chronokv95playground_u520(t_p0) {
  var result_553648651 = false;

  var F = {procname: "mustRehash.mustRehash", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/hashcommon.nim", line: 0};
  framePtr = F;
    if (!((t_p0.counter < (t_p0.data).length))) {
    F.line = 34;
    F.filename = "hashcommon.nim";
    failedAssertImpl__stdZassertions_u86(makeNimstrLit("/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/hashcommon.nim(34, 9) `\x0At.counter < t.dataLen` "));
    }
    
    F.line = 35;
    result_553648651 = (((t_p0.data).length < addInt(t_p0.counter, divInt(t_p0.counter, 2))) || (subInt((t_p0.data).length, t_p0.counter) < 4));
  framePtr = F.prev;

  return result_553648651;

}

function rawInsert__j0395chronokv95playground_u937(t_p0, data_p1, data_p1_Idx, key_p2, val_p3, hc_p4, h_p5) {
  var F = {procname: "rawInsert.rawInsert", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/tableimpl.nim", line: 0};
  framePtr = F;
    F.line = 25;
    F.filename = "tableimpl.nim";
    data_p1[data_p1_Idx][chckIndx(h_p5, 0, (data_p1[data_p1_Idx]).length - 1)].Field1 = nimCopy(null, key_p2, NTI33554449);
    F.line = 26;
    data_p1[data_p1_Idx][chckIndx(h_p5, 0, (data_p1[data_p1_Idx]).length - 1)].Field2 = nimCopy(null, val_p3, NTI33554449);
    F.line = 27;
    data_p1[data_p1_Idx][chckIndx(h_p5, 0, (data_p1[data_p1_Idx]).length - 1)].Field0 = hc_p4;
  framePtr = F.prev;

  
}

function enlarge__j0395chronokv95playground_u663(t_p0) {
  var F = {procname: "enlarge.enlarge", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/tables.nim", line: 0};
  framePtr = F;
    F.line = 247;
    F.filename = "tables.nim";
    var n_553648797 = [];
    F.line = 248;
    n_553648797 = new Array(chckRange(mulInt((t_p0.data).length, 2), 0, 2147483647)); for (var i = 0 ; i < chckRange(mulInt((t_p0.data).length, 2), 0, 2147483647) ; ++i) { n_553648797[i] = {Field0: 0, Field1: [], Field2: []}; }    F.line = 249;
    F.line = 249;
    var HEX3Atmp_553649745 = nimCopy(null, t_p0.data, NTI553648142);
    F.line = 249;
    t_p0.data = n_553648797;
    F.line = 249;
    n_553648797 = HEX3Atmp_553649745;
    Label1: {
      F.line = 250;
      var i_553648857 = 0;
      F.line = 46;
      F.filename = "iterators_1.nim";
      var colontmp__553649741 = 0;
      F.line = 250;
      F.filename = "tables.nim";
      colontmp__553649741 = (n_553648797).length - 1;
      F.line = 68;
      F.filename = "iterators_1.nim";
      var res_553649743 = 0;
      Label2: {
        F.line = 69;
          Label3: while (true) {
          if (!(res_553649743 <= colontmp__553649741)) break Label3;
            F.line = 250;
            F.filename = "tables.nim";
            i_553648857 = res_553649743;
            F.line = 251;
            var eh_553648907 = n_553648797[chckIndx(i_553648857, 0, (n_553648797).length - 1)].Field0;
            if (isFilled__pureZcollectionsZtables_u31(eh_553648907)) {
            F.line = 253;
            var j_553648911 = (eh_553648907 & (t_p0.data).length - 1);
            Label4: {
              F.line = 254;
                Label5: while (true) {
                if (!isFilled__pureZcollectionsZtables_u31(t_p0.data[chckIndx(j_553648911, 0, (t_p0.data).length - 1)].Field0)) break Label5;
                  F.line = 255;
                  j_553648911 = nextTry__pureZcollectionsZtables_u34(j_553648911, (t_p0.data).length - 1);
                }
            };
            F.line = 257;
            rawInsert__j0395chronokv95playground_u937(t_p0, t_p0, "data", n_553648797[chckIndx(i_553648857, 0, (n_553648797).length - 1)].Field1, n_553648797[chckIndx(i_553648857, 0, (n_553648797).length - 1)].Field2, eh_553648907, j_553648911);
            }
            
            F.line = 74;
            F.filename = "iterators_1.nim";
            res_553649743 = addInt(res_553649743, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function rawGetKnownHC__j0395chronokv95playground_u1094(t_p0, key_p1, hc_p2) {
  var result_553649228 = 0;

  var F = {procname: "rawGetKnownHC.rawGetKnownHC", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/hashcommon.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if (((t_p0.data).length == 0)) {
    F.line = 43;
    F.filename = "hashcommon.nim";
    result_553649228 = (-1);
    break BeforeRet;
    }
    
    F.line = 44;
    var h_553649275 = (hc_p2 & (t_p0.data).length - 1);
    Label1: {
      F.line = 45;
        Label2: while (true) {
        if (!isFilled__pureZcollectionsZtables_u31(t_p0.data[chckIndx(h_553649275, 0, (t_p0.data).length - 1)].Field0)) break Label2;
          if (((t_p0.data[chckIndx(h_553649275, 0, (t_p0.data).length - 1)].Field0 == hc_p2) && eqStrings(t_p0.data[chckIndx(h_553649275, 0, (t_p0.data).length - 1)].Field1, key_p1))) {
          F.line = 51;
          result_553649228 = h_553649275;
          break BeforeRet;
          }
          
          F.line = 52;
          h_553649275 = nextTry__pureZcollectionsZtables_u34(h_553649275, (t_p0.data).length - 1);
        }
    };
    F.line = 53;
    result_553649228 = subInt((-1), h_553649275);
  };
  framePtr = F.prev;

  return result_553649228;

}

function HEX5BHEX5DHEX3D__j0395chronokv95playground_u137(t_p0, key_p1, val_p2) {
  var F = {procname: "[]=.[]=", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/tables.nim", line: 0};
  framePtr = F;
    if (((t_p0.data).length == 0)) {
    F.line = 182;
    F.filename = "tableimpl.nim";
    var correctSizeHEX60gensym3_553648316 = slotsNeeded__pureZcollectionsZtables_u42(32);
    F.line = 186;
    t_p0.counter = 0;
    F.line = 187;
    t_p0.data = new Array(chckRange(correctSizeHEX60gensym3_553648316, 0, 2147483647)); for (var i = 0 ; i < chckRange(correctSizeHEX60gensym3_553648316, 0, 2147483647) ; ++i) { t_p0.data[i] = {Field0: 0, Field1: [], Field2: []}; }    }
    
    F.line = 59;
    var hc_553648326 = [0];
    F.line = 60;
    var index_553648549 = rawGet__j0395chronokv95playground_u199(t_p0, key_p1, hc_553648326, 0);
    if ((0 <= index_553648549)) {
    F.line = 61;
    t_p0.data[chckIndx(index_553648549, 0, (t_p0.data).length - 1)].Field2 = nimCopy(null, val_p2, NTI33554449);
    }
    else {
      if (((t_p0.data).length == 0)) {
      F.line = 182;
      var correctSizeHEX60gensym8_553648643 = slotsNeeded__pureZcollectionsZtables_u42(32);
      F.line = 186;
      t_p0.counter = 0;
      F.line = 187;
      t_p0.data = new Array(chckRange(correctSizeHEX60gensym8_553648643, 0, 2147483647)); for (var i = 0 ; i < chckRange(correctSizeHEX60gensym8_553648643, 0, 2147483647) ; ++i) { t_p0.data[i] = {Field0: 0, Field1: [], Field2: []}; }      }
      
      if (mustRehash__j0395chronokv95playground_u520(t_p0)) {
      F.line = 51;
      enlarge__j0395chronokv95playground_u663(t_p0);
      F.line = 52;
      index_553648549 = rawGetKnownHC__j0395chronokv95playground_u1094(t_p0, key_p1, hc_553648326[0]);
      }
      
      F.line = 53;
      index_553648549 = subInt((-1), index_553648549);
      F.line = 54;
      rawInsert__j0395chronokv95playground_u937(t_p0, t_p0, "data", key_p1, val_p2, hc_553648326[0], index_553648549);
      F.line = 62;
      t_p0.counter = addInt(t_p0.counter, 1);
    }
    
  framePtr = F.prev;

  
}

function put__j0395chronokv95playground_u97(mem_p0, key_p1, val_p2) {
  var F = {procname: "j03_chronokv_playground.put", prev: framePtr, filename: "/home/narayanas/projects/compound/js_suite/j03_chronokv_playground.nim", line: 0};
  framePtr = F;
    F.line = 14;
    F.filename = "j03_chronokv_playground.nim";
    HEX5BHEX5DHEX3D__j0395chronokv95playground_u137(mem_p0.kvStore, key_p1, val_p2);
  framePtr = F.prev;

  
}

function hasKey__j0395chronokv95playground_u1356(t_p0, key_p1) {
  var result_553649489 = false;

  var F = {procname: "hasKey.hasKey", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/tables.nim", line: 0};
  framePtr = F;
    F.line = 370;
    F.filename = "tables.nim";
    var hc_553649490 = [0];
    F.line = 371;
    result_553649489 = (0 <= rawGet__j0395chronokv95playground_u199(t_p0, key_p1, hc_553649490, 0));
  framePtr = F.prev;

  return result_553649489;

}

function raiseKeyError__j0395chronokv95playground_u1481(key_p0) {
  var F = {procname: "raiseKeyError.raiseKeyError", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/tables.nim", line: 0};
  framePtr = F;
    F.line = 232;
    F.filename = "tables.nim";
    raiseException({message: ([107,101,121,32,110,111,116,32,102,111,117,110,100,58,32]).concat(key_p0), parent: null, m_type: NTI134217747, name: null, trace: [], up: null}, "KeyError");
  framePtr = F.prev;

  
}

function HEX5BHEX5D__j0395chronokv95playground_u1418(t_p0, key_p1) {
  var result_553649551 = [];

  var F = {procname: "[].[]", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/tables.nim", line: 0};
  framePtr = F;
    F.line = 240;
    F.filename = "tables.nim";
    var hcHEX60gensym20_553649552 = [0];
    F.line = 241;
    var indexHEX60gensym20_553649559 = rawGet__j0395chronokv95playground_u199(t_p0, key_p1, hcHEX60gensym20_553649552, 0);
    if ((0 <= indexHEX60gensym20_553649559)) {
    F.line = 242;
    result_553649551 = t_p0.data[chckIndx(indexHEX60gensym20_553649559, 0, (t_p0.data).length - 1)]["Field2"];
    }
    else {
      F.line = 244;
    raiseKeyError__j0395chronokv95playground_u1481(key_p1);
    }
    
  framePtr = F.prev;

  return result_553649551;

}

function get__j0395chronokv95playground_u1316(mem_p0, key_p1) {
  var result_553649447 = [];

  var F = {procname: "j03_chronokv_playground.get", prev: framePtr, filename: "/home/narayanas/projects/compound/js_suite/j03_chronokv_playground.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if (hasKey__j0395chronokv95playground_u1356(mem_p0.kvStore, key_p1)) {
    F.line = 18;
    F.filename = "j03_chronokv_playground.nim";
    result_553649447 = nimCopy(null, HEX5BHEX5D__j0395chronokv95playground_u1418(mem_p0.kvStore, key_p1), NTI33554449);
    break BeforeRet;
    }
    else {
      F.line = 20;
      result_553649447 = nimCopy(null, [78,79,84,95,70,79,85,78,68], NTI33554449);
      break BeforeRet;
    }
    
  };
  framePtr = F.prev;

  return result_553649447;

}

function len__j0395chronokv95playground_u1567(t_p0) {
  var result_553649699 = 0;

  var F = {procname: "len.len", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/tables.nim", line: 0};
  framePtr = F;
    F.line = 495;
    F.filename = "tables.nim";
    result_553649699 = t_p0.counter;
  framePtr = F.prev;

  return result_553649699;

}
var F = {procname: "module j03_chronokv_playground", prev: framePtr, filename: "/home/narayanas/projects/compound/js_suite/j03_chronokv_playground.nim", line: 0};
framePtr = F;
F.line = 22;
F.filename = "j03_chronokv_playground.nim";
var db_553649649 = [createMemTable__j0395chronokv95playground_u13(1000)];
Label1: {
  F.line = 23;
  var i_553649654 = [0];
  F.line = 96;
  F.filename = "iterators_1.nim";
  var res_553649717 = 1;
  Label2: {
    F.line = 97;
      Label3: while (true) {
      if (!(res_553649717 <= 500)) break Label3;
        F.line = 23;
        F.filename = "j03_chronokv_playground.nim";
        i_553649654[0] = res_553649717;
        F.line = 24;
        put__j0395chronokv95playground_u97(db_553649649[0], ([107,101,121,95]).concat(HEX24__systemZdollars_u14(i_553649654[0])), ([118,97,108,117,101,95,100,97,116,97,95]).concat(HEX24__systemZdollars_u14(i_553649654[0])));
        F.line = 102;
        F.filename = "iterators_1.nim";
        res_553649717 = addInt(res_553649717, 1);
      }
  };
};
F.line = 26;
F.filename = "j03_chronokv_playground.nim";
rawEcho([91,51,47,49,48,32,80,65,83,83,69,68,93,32,67,104,114,111,110,111,75,86,32,87,101,98,32,80,108,97,121,103,114,111,117,110,100,32,45,32,75,101,121,32,39,107,101,121,95,50,53,48,39,58], get__j0395chronokv95playground_u1316(db_553649649[0], [107,101,121,95,50,53,48]), [124,32,84,111,116,97,108,32,77,101,109,84,97,98,108,101,32,75,101,121,115,58], HEX24__systemZdollars_u14(len__j0395chronokv95playground_u1567(db_553649649[0].kvStore)));
framePtr = F.prev;
var F = {procname: "module j03_chronokv_playground", prev: framePtr, filename: "/home/narayanas/projects/compound/js_suite/j03_chronokv_playground.nim", line: 0};
framePtr = F;
framePtr = F.prev;
