/* Generated by the Nim Compiler v2.2.10 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI553648131 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555185 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217746 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217742 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555870 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555187 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555186 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555184 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI687866237 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
NTI687866237.base = NTI33554449;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
var NNI33555184 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555184.node = NNI33555184;
NTI33555186.base = NTI33555183;
NTI33555187.base = NTI33555183;
var NNI33555183 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555186, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555187, name: "up", sons: null}]};
NTI33555183.node = NNI33555183;
var NNI33555179 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555179.node = NNI33555179;
NTI33555183.base = NTI33555179;
NTI33555184.base = NTI33555183;
NTI134217749.base = NTI33555184;
var NNI33555870 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555870.node = NNI33555870;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
NTI134217741.base = NTI33555184;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555184;
var NNI134217742 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217742.node = NNI134217742;
NTI134217742.base = NTI134217741;
var NNI134217746 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217746.node = NNI134217746;
var NNI33555185 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555185.node = NNI33555185;
NTI33555185.base = NTI33555183;
NTI134217746.base = NTI33555185;
var NNI553648131 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI33554435, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI33554435, name: "y", sons: null}, 
{kind: 1, offset: "color", len: 0, typ: NTI33554449, name: "color", sons: null}]};
NTI553648131.node = NNI553648131;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557376 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2924(ti_p2))) {
      result_33557376 = src_p1;
      }
      else {
        result_33557376 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557376 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557376 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557376 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557376 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557376, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557376 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557376 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557376 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557376[i] = nimCopy(result_33557376[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557376 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557376 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557376[i] = nimCopy(result_33557376[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557376 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557376 = src_p1;
      break;
    }

  return result_33557376;

}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function nimAddStrStr(x_p0, y_p1) {
      var L = y_p1.length;
  for (var i = 0; i < L; ++i) {
    x_p0.push(y_p1[i]);
  }
  

  
}

function arrayConstr(len_p0, value_p1, typ_p2) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; ++i) result[i] = nimCopy(null, value_p1, typ_p2);
    return result;
  

  
}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function isObj(obj_p0, subclass_p1) {
  var result_33557489 = false;

  BeforeRet: {
    var x_33557490 = obj_p0;
    if ((x_33557490 == subclass_p1)) {
    result_33557489 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557490 == subclass_p1))) break Label2;
          if ((x_33557490 == null)) {
          result_33557489 = false;
          break BeforeRet;
          }
          
          x_33557490 = x_33557490.base;
        }
    };
    result_33557489 = true;
    break BeforeRet;
  };

  return result_33557489;

}

function toJSStr(s_p0) {
  var result_33556953 = null;

    var res_33557019 = newSeq__system_u2562((s_p0).length);
    var i_33557020 = 0;
    var j_33557021 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33557020 < (s_p0).length)) break Label2;
          var c_33557022 = s_p0[i_33557020];
          if ((c_33557022 < 128)) {
          res_33557019[j_33557021] = String.fromCharCode(c_33557022);
          i_33557020 += 1;
          }
          else {
            var helper_33557048 = newSeq__system_u2562(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557049 = c_33557022.toString(16);
                  if ((((code_33557049) == null ? 0 : (code_33557049).length) == 1)) {
                  helper_33557048.push("%0");;
                  }
                  else {
                  helper_33557048.push("%");;
                  }
                  
                  helper_33557048.push(code_33557049);;
                  i_33557020 += 1;
                  if ((((s_p0).length <= i_33557020) || (s_p0[i_33557020] < 128))) {
                  break Label3;
                  }
                  
                  c_33557022 = s_p0[i_33557020];
                }
            };
++excHandler;
            try {
            res_33557019[j_33557021] = decodeURIComponent(helper_33557048.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33557019[j_33557021] = helper_33557048.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33557021 += 1;
        }
    };
    if (res_33557019.length < j_33557021) { for (var i = res_33557019.length ; i < j_33557021 ; ++i) res_33557019.push(null); }
               else { res_33557019.length = j_33557021; };
    result_33556953 = res_33557019.join("");

  return result_33556953;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    e_p0.trace = nimCopy(null, rawWriteStackTrace__system_u2214(), NTI33554449);
    throw e_p0;

  
}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557411 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557411 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557411;

}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function nimMax(a_p0, b_p1) {
    var Temporary1;

  var result_33557203 = 0;

  BeforeRet: {
    if ((b_p1 <= a_p0)) {
    Temporary1 = a_p0;
    }
    else {
    Temporary1 = b_p1;
    }
    
    result_33557203 = Temporary1;
    break BeforeRet;
  };

  return result_33557203;

}

function nimMin(a_p0, b_p1) {
    var Temporary1;

  var result_33557199 = 0;

  BeforeRet: {
    if ((a_p0 <= b_p1)) {
    Temporary1 = a_p0;
    }
    else {
    Temporary1 = b_p1;
    }
    
    result_33557199 = Temporary1;
    break BeforeRet;
  };

  return result_33557199;

}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557416 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557416 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557416;

}
var ConstSet2 = setConstr([48, 57]);
var ConstSet3 = setConstr([48, 57]);

function divInt64(a_p0, b_p1) {
        if (b_p1 == 0n) raiseDivByZero();
    if (b_p1 == -1n && a_p0 == 9223372036854775807n) raiseOverflow();
    return a_p0 / b_p1;
  

  
}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer__system_u2924(ti_p0) {
  var result_33557358 = false;

  BeforeRet: {
    result_33557358 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557358;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_335544528 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = (old_335544528 + n_p3), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_335544542 = 0;
      var i_553648182 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_553648182 < n_p3)) break Label4;
            iHEX60gensym4_335544542 = i_553648182;
            result_p0[result_p0_Idx][(old_335544528 + iHEX60gensym4_335544542)] = x_p1.charCodeAt((start_p2 + iHEX60gensym4_335544542));
            i_553648182 += 1;
          }
      };
    };

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));

  
}

function HEX24__systemZdollars_u14(xHEX60gensym0_p0) {
  var result_385875984 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 20;
    F.filename = "dollars.nim";
    result_385875984[0] = nimCopy(null, [], NTI33554449);
    F.line = 21;
    addInt__stdZprivateZdigitsutils_u241(result_385875984, 0, xHEX60gensym0_p0);
  framePtr = F.prev;

  return result_385875984[0];

}

function packDrawEvent__j0795websocket95canvas_u6(ev_p0) {
  var result_553648136 = [];

  var F = {procname: "j07_websocket_canvas.packDrawEvent", prev: framePtr, filename: "/home/narayanas/projects/compound/js_suite/j07_websocket_canvas.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 12;
    F.filename = "j07_websocket_canvas.nim";
    result_553648136 = nimCopy(null, (HEX24__systemZdollars_u14(ev_p0.x)).concat([44],HEX24__systemZdollars_u14(ev_p0.y),[44],ev_p0.color), NTI33554449);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_553648136;

}

function add__system_u1972(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function auxWriteStackTrace__system_u2116(f_p0) {
  var result_33556550 = [[]];

    var it_33556558 = f_p0;
    var i_33556559 = 0;
    var total_33556560 = 0;
    var tempFrames_33556561 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555870);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556558 == null)) && (i_33556559 <= 63))) break Label2;
          tempFrames_33556561[i_33556559].Field0 = it_33556558.procname;
          tempFrames_33556561[i_33556559].Field1 = it_33556558.line;
          tempFrames_33556561[i_33556559].Field2 = it_33556558.filename;
          i_33556559 += 1;
          total_33556560 += 1;
          it_33556558 = it_33556558.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556558 == null))) break Label4;
          total_33556560 += 1;
          it_33556558 = it_33556558.prev;
        }
    };
    result_33556550[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556560 == i_33556559))) {
    nimAddStrStr(result_33556550[0], [40]);;
    nimAddStrStr(result_33556550[0], HEX24__systemZdollars_u14((total_33556560 - i_33556559)));;
    nimAddStrStr(result_33556550[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556594 = 0;
      var colontmp__553648195 = 0;
      colontmp__553648195 = (i_33556559 - 1);
      var res_553648197 = colontmp__553648195;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_553648197)) break Label7;
            j_33556594 = res_553648197;
            nimAddStrStr(result_33556550[0], cstrToNimstr(tempFrames_33556561[j_33556594].Field2));;
            if ((0 < tempFrames_33556561[j_33556594].Field1)) {
            nimAddStrStr(result_33556550[0], [40]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556550, 0, tempFrames_33556561[j_33556594].Field1);
            if (false) {
            nimAddStrStr(result_33556550[0], [44,32]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556550, 0, 0);
            }
            
            nimAddStrStr(result_33556550[0], [41]);;
            }
            
            nimAddStrStr(result_33556550[0], [32,97,116,32]);;
            add__system_u1972(result_33556550, 0, tempFrames_33556561[j_33556594].Field0);
            nimAddStrStr(result_33556550[0], [10]);;
            res_553648197 -= 1;
          }
      };
    };

  return result_33556550[0];

}

function rawWriteStackTrace__system_u2214() {
  var result_33556647 = [];

    if (!((framePtr == null))) {
    result_33556647 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10]).concat(auxWriteStackTrace__system_u2116(framePtr)), NTI33554449);
    }
    else {
      result_33556647 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556647;

}

function newSeq__system_u2562(len_p0) {
  var result_33556998 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 651;
    F.filename = "system.nim";
    result_33556998 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556998[i] = null; }  framePtr = F.prev;

  return result_33556998;

}

function isNimException__system_u2047() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556482 = null;

    if (isNimException__system_u2047()) {
    result_33556482 = lastJSError;
    }
    

  return result_33556482;

}

function raiseDefect() {
    if (isNimException__system_u2047()) {
    var e_33556698 = getCurrentException();
    if (isObj(e_33556698.m_type, NTI33555184)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556698);
    }
    
    e_33556698.trace = nimCopy(null, rawWriteStackTrace__system_u2214(), NTI33554449);
    throw e_33556698;
    }
    
    }
    

  
}

function unhandledException(e_p0) {
    var buf_33556692 = [[]];
    if (!(((e_p0.message).length == 0))) {
    nimAddStrStr(buf_33556692[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    nimAddStrStr(buf_33556692[0], e_p0.message);;
    }
    else {
    nimAddStrStr(buf_33556692[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    nimAddStrStr(buf_33556692[0], [32,91]);;
    add__system_u1972(buf_33556692, 0, e_p0.name);
    nimAddStrStr(buf_33556692[0], [93,10]);;
    nimAddStrStr(buf_33556692[0], rawWriteStackTrace__system_u2214());;
    var cbuf_33556693 = toJSStr(buf_33556692[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556693);
  }
  else {
    throw cbuf_33556693;
  }
  

  
}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u14(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u14(a_p1),[32,46,46,32],HEX24__systemZdollars_u14(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function substr__system_u3776(s_p0, first_p1, last_p2) {
  var result_33558212 = [];

  var F = {procname: "system.substr", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 2946;
    F.filename = "system.nim";
    var first_33558213 = nimMax(first_p1, 0);
    F.line = 2947;
    var last_33558214 = nimMin(last_p2, (s_p0).length - 1);
    F.line = 2948;
    var L_33558215 = nimMax(addInt(subInt(last_33558214, first_33558213), 1), 0);
    F.line = 2949;
    result_33558212 = nimCopy(null, mnewString(chckRange(L_33558215, 0, 2147483647)), NTI33554449);
    Label1: {
      F.line = 2954;
      var i_33558225 = 0;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_553648206 = 0;
      Label2: {
        F.line = 129;
          Label3: while (true) {
          if (!(i_553648206 < L_33558215)) break Label3;
            F.line = 2954;
            F.filename = "system.nim";
            i_33558225 = i_553648206;
            F.line = 2955;
            result_33558212[chckIndx(i_33558225, 0, (result_33558212).length - 1)] = s_p0[chckIndx(addInt(i_33558225, first_33558213), 0, (s_p0).length - 1)];
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_553648206 = addInt(i_553648206, 1);
          }
      };
    };
  framePtr = F.prev;

  return result_33558212;

}

function nsuSplitChar(s_p0, sep_p1, maxsplit_p2) {
  var result_687866405 = [];

  var F = {procname: "strutils.split", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 418;
    F.filename = "strutils.nim";
    result_687866405 = nimCopy(null, [], NTI687866237);
    Label1: {
      F.line = 419;
      var xHEX60gensym67_687866411 = [];
      F.line = 390;
      var lastHEX60gensym34_553648187 = 0;
      F.line = 391;
      var splitsHEX60gensym34_553648188 = maxsplit_p2;
      Label2: {
        F.line = 450;
          Label3: while (true) {
          if (!(lastHEX60gensym34_553648187 <= (s_p0).length)) break Label3;
            F.line = 394;
            var firstHEX60gensym34_553648190 = lastHEX60gensym34_553648187;
            Label4: {
              F.line = 395;
                Label5: while (true) {
                if (!((lastHEX60gensym34_553648187 < (s_p0).length) && !((s_p0[chckIndx(lastHEX60gensym34_553648187, 0, (s_p0).length - 1)] == sep_p1)))) break Label5;
                  F.line = 396;
                  lastHEX60gensym34_553648187 = addInt(lastHEX60gensym34_553648187, 1);
                }
            };
            if ((splitsHEX60gensym34_553648188 == 0)) {
            F.line = 397;
            lastHEX60gensym34_553648187 = (s_p0).length;
            }
            
            F.line = 760;
            xHEX60gensym67_687866411 = substr__system_u3776(s_p0, firstHEX60gensym34_553648190, subInt(lastHEX60gensym34_553648187, 1));
            F.line = 419;
            var Temporary6 = nimCopy(null, xHEX60gensym67_687866411, NTI33554449);
            result_687866405.push(Temporary6);;
            if ((splitsHEX60gensym34_553648188 == 0)) {
            F.line = 399;
            break Label2;
            }
            
            F.line = 400;
            splitsHEX60gensym34_553648188 = subInt(splitsHEX60gensym34_553648188, 1);
            F.line = 401;
            lastHEX60gensym34_553648187 = addInt(lastHEX60gensym34_553648187, 1);
          }
      };
    };
  framePtr = F.prev;

  return result_687866405;

}

function raiseDivByZero() {
    raiseException({message: [100,105,118,105,115,105,111,110,32,98,121,32,122,101,114,111], parent: null, m_type: NTI134217742, name: null, trace: [], up: null}, "DivByZeroDefect");

  
}

function integerOutOfRangeError__pureZparseutils_u325() {
  var F = {procname: "parseutils.integerOutOfRangeError", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/parseutils.nim", line: 0};
  framePtr = F;
    F.line = 429;
    F.filename = "parseutils.nim";
    raiseException({message: [80,97,114,115,101,100,32,105,110,116,101,103,101,114,32,111,117,116,115,105,100,101,32,111,102,32,118,97,108,105,100,32,114,97,110,103,101], parent: null, m_type: NTI134217746, name: null, trace: [], up: null}, "ValueError");
  framePtr = F.prev;

  
}

function rawParseInt__pureZparseutils_u363(s_p0, b_p1, b_p1_Idx) {
      var Temporary1;
          var Temporary4;

  var result_704643438 = 0;

  var F = {procname: "parseutils.rawParseInt", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/parseutils.nim", line: 0};
  framePtr = F;
    F.line = 437;
    F.filename = "parseutils.nim";
    var sign_704643439 = (-1n);
    F.line = 438;
    var i_704643440 = 0;
    if ((i_704643440 < (s_p0).length)) {
    if ((s_p0[chckIndx(i_704643440, 0, (s_p0).length - 1)] == 43)) {
    F.line = 440;
    i_704643440 += 1;
    }
    else {
    if ((s_p0[chckIndx(i_704643440, 0, (s_p0).length - 1)] == 45)) {
    F.line = 442;
    i_704643440 += 1;
    F.line = 443;
    sign_704643439 = 1n;
    }
    }
    }
    
      if (!(i_704643440 < (s_p0).length)) Temporary1 = false; else {        Temporary1 = (ConstSet2[s_p0[chckIndx(i_704643440, 0, (s_p0).length - 1)]] != undefined);      }    if (Temporary1) {
    F.line = 445;
    b_p1[b_p1_Idx] = 0n;
    Label2: {
      F.line = 446;
        Label3: while (true) {
          if (!(i_704643440 < (s_p0).length)) Temporary4 = false; else {            Temporary4 = (ConstSet3[s_p0[chckIndx(i_704643440, 0, (s_p0).length - 1)]] != undefined);          }        if (!Temporary4) break Label3;
          F.line = 447;
          var c_704643474 = (s_p0[chckIndx(i_704643440, 0, (s_p0).length - 1)] - 48);
          if ((((-9223372036854775808n) + BigInt(c_704643474)) / 10n <= b_p1[b_p1_Idx])) {
          F.line = 449;
          b_p1[b_p1_Idx] = ((b_p1[b_p1_Idx] * 10n) - BigInt(c_704643474));
          }
          else {
            F.line = 451;
          integerOutOfRangeError__pureZparseutils_u325();
          }
          
          F.line = 452;
          i_704643440 += 1;
          Label5: {
            F.line = 453;
              Label6: while (true) {
              if (!((i_704643440 < (s_p0).length) && (s_p0[chckIndx(i_704643440, 0, (s_p0).length - 1)] == 95))) break Label6;
                F.line = 453;
                i_704643440 += 1;
              }
          };
        }
    };
    if (((sign_704643439 == (-1n)) && (b_p1[b_p1_Idx] == (-9223372036854775808n)))) {
    F.line = 455;
    integerOutOfRangeError__pureZparseutils_u325();
    }
    else {
      F.line = 457;
      b_p1[b_p1_Idx] = (b_p1[b_p1_Idx] * sign_704643439);
      F.line = 458;
      result_704643438 = i_704643440;
    }
    
    }
    else {
      F.line = 460;
      result_704643438 = 0;
    }
    
  framePtr = F.prev;

  return result_704643438;

}

function npuParseBiggestInt(s_p0, number_p1, number_p1_Idx) {
  var result_704643499 = 0;

  var F = {procname: "parseutils.parseBiggestInt", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/parseutils.nim", line: 0};
  framePtr = F;
    F.line = 476;
    F.filename = "parseutils.nim";
    var res_704643500 = [0n];
    F.line = 479;
    result_704643499 = rawParseInt__pureZparseutils_u363(s_p0, res_704643500, 0);
    if (!((result_704643499 == 0))) {
    F.line = 481;
    number_p1[number_p1_Idx] = res_704643500[0];
    }
    
  framePtr = F.prev;

  return result_704643499;

}

function npuParseInt(s_p0, number_p1, number_p1_Idx) {
  var result_704643504 = 0;

  var F = {procname: "parseutils.parseInt", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/parseutils.nim", line: 0};
  framePtr = F;
    F.line = 492;
    F.filename = "parseutils.nim";
    var res_704643505 = [0n];
    F.line = 493;
    result_704643504 = npuParseBiggestInt(s_p0, res_704643505, 0);
    if (((res_704643505[0] < (-2147483648n)) || (2147483647n < res_704643505[0]))) {
    F.line = 496;
    integerOutOfRangeError__pureZparseutils_u325();
    }
    
    if (!((result_704643504 == 0))) {
    F.line = 498;
    number_p1[number_p1_Idx] = chckRange(Number(res_704643505[0]), (-2147483648), 2147483647);
    }
    
  framePtr = F.prev;

  return result_704643504;

}

function parseInt__pureZparseutils_u951(s_p0, number_p1, number_p1_Idx, start_p2) {
  var result_704644027 = 0;

  var F = {procname: "parseutils.parseInt", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/parseutils.nim", line: 0};
  framePtr = F;
    F.line = 1019;
    F.filename = "parseutils.nim";
    result_704644027 = npuParseInt((s_p0.slice(start_p2, (s_p0).length - 1 + 1)), number_p1, number_p1_Idx);
  framePtr = F.prev;

  return result_704644027;

}

function nsuParseInt(s_p0) {
  var result_687866715 = [0];

  var F = {procname: "strutils.parseInt", prev: framePtr, filename: "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 1157;
    F.filename = "strutils.nim";
    result_687866715[0] = 0;
    F.line = 1158;
    var L_687866716 = parseInt__pureZparseutils_u951(s_p0, result_687866715, 0, 0);
    if ((!((L_687866716 == (s_p0).length)) || (L_687866716 == 0))) {
    F.line = 1160;
    raiseException({message: ([105,110,118,97,108,105,100,32,105,110,116,101,103,101,114,58,32]).concat(s_p0), parent: null, m_type: NTI134217746, name: null, trace: [], up: null}, "ValueError");
    }
    
  framePtr = F.prev;

  return result_687866715[0];

}

function unpackDrawEvent__j0795websocket95canvas_u9(packet_p0) {
  var result_553648139 = ({x: 0, y: 0, color: []});

  var F = {procname: "j07_websocket_canvas.unpackDrawEvent", prev: framePtr, filename: "/home/narayanas/projects/compound/js_suite/j07_websocket_canvas.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 15;
    F.filename = "j07_websocket_canvas.nim";
    var parts_553648140 = nsuSplitChar(packet_p0, 44, (-1));
    F.line = 16;
    result_553648139 = nimCopy(result_553648139, {x: nsuParseInt(parts_553648140[chckIndx(0, 0, (parts_553648140).length - 1)]), y: nsuParseInt(parts_553648140[chckIndx(1, 0, (parts_553648140).length - 1)]), color: nimCopy(null, parts_553648140[chckIndx(2, 0, (parts_553648140).length - 1)], NTI33554449)}, NTI553648131);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_553648139;

}
var F = {procname: "module j07_websocket_canvas", prev: framePtr, filename: "/home/narayanas/projects/compound/js_suite/j07_websocket_canvas.nim", line: 0};
framePtr = F;
F.line = 18;
F.filename = "j07_websocket_canvas.nim";
var ev_553648159 = [{x: 250, y: 400, color: [35,70,70,48,48,48,48]}];
F.line = 19;
var packed_553648160 = [packDrawEvent__j0795websocket95canvas_u6(ev_553648159[0])];
F.line = 20;
var unpacked_553648161 = [unpackDrawEvent__j0795websocket95canvas_u9(packed_553648160[0])];
F.line = 22;
rawEcho([91,55,47,49,48,32,80,65,83,83,69,68,93,32,87,101,98,83,111,99,107,101,116,32,80,114,111,116,111,99,111,108,32,80,97,99,107,101,116,58], packed_553648160[0], [124,32,85,110,112,97,99,107,101,100,32,88,58], HEX24__systemZdollars_u14(unpacked_553648161[0].x), [89,58], HEX24__systemZdollars_u14(unpacked_553648161[0].y), [67,111,108,111,114,58], unpacked_553648161[0].color);
framePtr = F.prev;
var F = {procname: "module j07_websocket_canvas", prev: framePtr, filename: "/home/narayanas/projects/compound/js_suite/j07_websocket_canvas.nim", line: 0};
framePtr = F;
framePtr = F.prev;
